// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MFSAPI.Models
{
    public partial class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public int PersonId { get; set; }
        public int GenreId { get; set; }
        public int? Rating { get; set; }

        [JsonIgnore]
        public virtual Genre Genre { get; set; }

        [JsonIgnore]
        public virtual Person Person { get; set; }
    }
}